6. 异常

6.1 解释下异常

6.2 Error和Exception的区别

6.3 异常的分类

6.4 throw和throws的区别

throw表示抛出某个异常，用于函数内部，当方法内部出现了逻辑错误后由程序员主动定义抛出异常
throws表示可能存在某种异常，用于方法声明，最终会讲对应的异常交由上层调用这个方法的其他方法来处理

throw异常以后，要用try{...}catch{...}捕获，如果有IO流，一定记得要及时关闭（要么在catch中关闭，要么再写个finally关闭），函数体内如果throw了异常，也要在方法声明时throws，交由上层调用函数处理或者直接在本方法内try..catch..